export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
// Registrar usuario
export const REGISTRO_USUARIO = 'REGISTRO_USUARIO';
export const REGISTRO_USUARIO_EXITOSO = 'REGISTRO_USUARIO_EXITOSO';
export const REGISTRO_USUARIO_ERROR = 'REGISTRO_USUARIO_ERROR';
export const RESET_AUTH_MESSAGE = 'RESET_AUTH_MESSAGE';
// Login usuario
export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const LOGIN_USUARIO_EXITOSO = 'LOGIN_USUARIO_EXITOSO';
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR';
// Obtener usuario
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIO_EXITO = 'OBTENER_USUARIO_EXITO';
export const OBTENER_USUARIO_ERROR = 'OBTENER_USUARIO_ERROR;'
// Cerrar sesión
export const CERRAR_SESION = 'CERRAR_SESION';

export const GET_USUARIOS = 'GET_USUARIOS'
export const SELECT_USER = 'SELECT_USER'
